class Spices {
  static const List<String> items = [
    'Salt',
    'Pepper',
    'Garlic',
    'Ginger',
    'Cumin',
    'Turmeric',
    'Paprika',
    'Coriander',
    'Cinnamon',
    'Nutmeg',
    'Clove',
    'Cardamom',
    'Saffron',
    'Mustard',
    'Fennel',
    'Fenugreek',
    'Bay Leaf',
    'Oregano',
    'Thyme',
    'Rosemary',
    'Basil',
    'Parsley',
    'Dill',
    'Chili Powder',
    'Cayenne',
    'Anise',
    'Allspice',
    'Caraway',
    'Celery Seed',
    'Chives',
    'Curry Powder',
    'Marjoram',
    'Mint',
    'Sage',
    'Tarragon',
    'Vanilla',
    'Wasabi',
    'Horseradish',
    'Lemongrass',
    'Mace',
    'Sumac',
    'Za\'atar',
    'Star Anise',
    'Szechuan Pepper',
    'White Pepper',
    'Black Pepper',
    'Pink Pepper',
    'Green Pepper',
    'Smoked Paprika',
    'Sweet Paprika',
  ];
}
